version: '3.7'
services:
  pgAdmin:
    image: dpage/pgadmin4:4.28
    ports: [ '9001:80' ]
    environment: [ PGADMIN_DEFAULT_EMAIL=admin@test.com, PGADMIN_DEFAULT_PASSWORD=admin ]
    restart: on-failure
  postgresql:
    # image: postgis/postgis:13-master
    # pgRouting Docker image (version 3.2.0) built over Postgres 13/PostGIS 3.1 and dependencies.
    image: pgrouting/pgrouting:latest
    ports: [ '5432:5432' ]
    environment: [ POSTGRES_PASSWORD=admin, POSTGRES_DB=postgres ]
    restart: on-failure
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"